version: "3.1"

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
  redis:
    image: redis
    ports:
      - 6379:6379
  adminer:
    image: adminer
    ports:
      - 8080:8080
