name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Setup NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Install PurgeCSS
      run: |
        npm install purgecss
    - name: Strip unused CSS
      run: |
        purgecss -css static/css/* -con templates/* -o static/css/
    - name: Run tests
      run: |
        go test -count=1 -v ./...
      env:
        BLOGGULUS_DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres
    - name: Build project
      run: |
        go build -o bloggulus main.go
    - name: Bundle project
      run: |
        mkdir dist/
        cp bloggulus dist/
        cp -r migrations dist/
        cp -r static dist/
        cp -r templates dist/
        tree dist/
    - name: Copy build artifacts
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.BLOGGULUS_HOSTNAME }}
        username: ${{ secrets.BLOGGULUS_SSH_USER }}
        key: ${{ secrets.BLOGGULUS_SSH_KEY }}
        source: dist/*
        strip_components: 1
        target: /home/${{ secrets.BLOGGULUS_SSH_USER }}/
    - name: Restart service
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.BLOGGULUS_HOSTNAME }}
        username: ${{ secrets.BLOGGULUS_SSH_USER }}
        key: ${{ secrets.BLOGGULUS_SSH_KEY }}
        script: |
          sudo systemctl restart bloggulus
