name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Setup NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Install PurgeCSS
      run: |
        npm install -g purgecss
    # intentionally absent from the Makefile due to destructive behavior
    - name: Strip unused CSS
      run: >
        purgecss
        -c scripts/purgecss.config.js
        -con templates/*.tmpl
        -css static/css/*
        -o static/css/
    - name: Run tests
      run: |
        make test
      env:
        BLOGGULUS_DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres
    - name: Build project
      run: |
        make
    - name: Copy build artifact
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.BLOGGULUS_HOSTNAME }}
        username: ${{ secrets.BLOGGULUS_SSH_USER }}
        key: ${{ secrets.BLOGGULUS_SSH_KEY }}
        source: bloggulus
        target: /home/${{ secrets.BLOGGULUS_SSH_USER }}/
    - name: Restart web service
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.BLOGGULUS_HOSTNAME }}
        username: ${{ secrets.BLOGGULUS_SSH_USER }}
        key: ${{ secrets.BLOGGULUS_SSH_KEY }}
        script: |
          sudo systemctl restart bloggulus
